### ISSUE TITLE
Doesn't work with authenticated sessions using cookies

### ISSUE THREAD

**Issue by osiloke** [olebedev/go-duktape-fetch#5]
server side fetch doesn't work well with session based authentication middlewares. The remote addr, as well some other request parameters, is not passed, hence most session based middlewares cannot validate the session. 

The alternative for making authenticated server calls seems to be to use a jwt which seems redundant.

Any thoughts?

**Comment by olebedev** [comment]
It's recommended to use JWT explicitly. Have a look at [this](https://github.com/olebedev/go-starter-kit/blob/master/server/react.go#L67) example.
